###############################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html
###############################################################################

# Book settings
title: Ph.D. Thesis
author: Zvi Baratz
copyright: "2021"
logo: logo.png
exclude_patterns: ["*skip*"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ZviBaratz/PhD
  path_to_book: src/book
  branch: master

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: favicon.jpg
  baseurl: "https://zvibaratz.github.io/phd/front.html"
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""

# Declare primary language.
# See: https://jupyterbook.org/advanced/html.html#configuring-to-improve-accessibility
sphinx:
  config:
    language: en
    bibtex_reference_style: author_year
    myst_substitutions:
      # Acronyms
      PREMUTED: '<span class="muted-ref">'
      POSTMUTED: "</span>"
      ABIDE: "{{ PREMUTED }}{ref}`ABIDE <lists:acronyms>`{{ POSTMUTED }}"
      ADNI: "{{ PREMUTED }}{ref}`ADNI <lists:acronyms>`{{ POSTMUTED }}"
      API: "{{ PREMUTED }}{ref}`API <lists:acronyms>`{{ POSTMUTED }}"
      BFI: "{{ PREMUTED }}{ref}`BFI <lists:acronyms>`{{ POSTMUTED }}"
      BIDS: "{{ PREMUTED }}{ref}`BIDS <lists:acronyms>`{{ POSTMUTED }}"
      CI: "{{ PREMUTED }}{ref}`CI <lists:acronyms>`{{ POSTMUTED }}"
      COINS: "{{ PREMUTED }}{ref}`COINS <lists:acronyms>`{{ POSTMUTED }}"
      CSS: "{{ PREMUTED }}{ref}`CSS <lists:acronyms>`{{ POSTMUTED }}"
      DBMS: "{{ PREMUTED }}{ref}`DBMS <lists:acronyms>`{{ POSTMUTED }}"
      DICOM: "{{ PREMUTED }}{ref}`DICOM <lists:acronyms>`{{ POSTMUTED }}"
      dMRI: "{{ PREMUTED }}{ref}`dMRI <lists:acronyms>`{{ POSTMUTED }}"
      EDA: "{{ PREMUTED }}{ref}`EDA <lists:acronyms>`{{ POSTMUTED }}"
      ER: "{{ PREMUTED }}{ref}`ER <lists:acronyms>`{{ POSTMUTED }}"
      fMRI: "{{ PREMUTED }}{ref}`fMRI <lists:acronyms>`{{ POSTMUTED }}"
      FOSS: "{{ PREMUTED }}{ref}`FOSS <lists:acronyms>`{{ POSTMUTED }}"
      GUI: "{{ PREMUTED }}{ref}`GUI <lists:acronyms>`{{ POSTMUTED }}"
      HCP: "{{ PREMUTED }}{ref}`HCP <lists:acronyms>`{{ POSTMUTED }}"
      HTML: "{{ PREMUTED }}{ref}`HTML <lists:acronyms>`{{ POSTMUTED }}"
      JSON: "{{ PREMUTED }}{ref}`JSON <lists:acronyms>`{{ POSTMUTED }}"
      JSP: "{{ PREMUTED }}{ref}`JSP <lists:acronyms>`{{ POSTMUTED }}"
      LORIS: "{{ PREMUTED }}{ref}`LORIS <lists:acronyms>`{{ POSTMUTED }}"
      MPRAGE: "{{ PREMUTED }}{ref}`MPRAGE <lists:acronyms>`{{ POSTMUTED }}"
      MR: "{{ PREMUTED }}{ref}`MR <lists:acronyms>`{{ POSTMUTED }}"
      MRI: "{{ PREMUTED }}{ref}`MRI <lists:acronyms>`{{ POSTMUTED }}"
      NIfTI: "{{ PREMUTED }}{ref}`NIfTI <lists:acronyms>`{{ POSTMUTED }}"
      ORM: "{{ PREMUTED }}{ref}`ORM <lists:acronyms>`{{ POSTMUTED }}"
      PHI: "{{ PREMUTED }}{ref}`PHI <lists:acronyms>`{{ POSTMUTED }}"
      PHP: "{{ PREMUTED }}{ref}`PHP <lists:acronyms>`{{ POSTMUTED }}"
      REST: "{{ PREMUTED }}{ref}`REST <lists:acronyms>`{{ POSTMUTED }}"
      RDBMS: "{{ PREMUTED }}{ref}`RDBMS <lists:acronyms>`{{ POSTMUTED }}"
      RDM: "{{ PREMUTED }}{ref}`RDM <lists:acronyms>`{{ POSTMUTED }}"
      rsfMRI: "{{ PREMUTED }}{ref}`rs-fMRI <lists:acronyms>`{{ POSTMUTED }}"
      SD: "{{ PREMUTED }}{ref}`SD <lists:acronyms>`{{ POSTMUTED }}"
      SFTP: "{{ PREMUTED }}{ref}`SFTP <lists:acronyms>`{{ POSTMUTED }}"
      sMRI: "{{ PREMUTED }}{ref}`sMRI <lists:acronyms>`{{ POSTMUTED }}"
      SNR: "{{ PREMUTED }}{ref}`SNR <lists:acronyms>`{{ POSTMUTED }}"
      SQL: "{{ PREMUTED }}{ref}`SQL <lists:acronyms>`{{ POSTMUTED }}"
      SSH: "{{ PREMUTED }}{ref}`SSH <lists:acronyms>`{{ POSTMUTED }}"
      T1w: "{{ PREMUTED }}{ref}`T1w <lists:acronyms>`{{ POSTMUTED }}"
      T2w: "{{ PREMUTED }}{ref}`T2w <lists:acronyms>`{{ POSTMUTED }}"
      XNAT: "{{ PREMUTED }}{ref}`XNAT <lists:acronyms>`{{ POSTMUTED }}"
      # HTML & CSS
      greenCheckmark: '<p class="table-icon" style="color: green;"><i class="fas fa-check-circle"></i></p>'
      greenCheckmarkStarred: '<p class="table-icon" style="color: green;"><i class="fas fa-check-circle"></i><span style="color: black;">*</span></p>'
      redCross: '<p class="table-icon" style="color: red;"><i class="fas fa-times-circle"></i></p>'
      # Other links
      Celery: "{{ PREMUTED }}[Celery](https://docs.celeryproject.org/){{ POSTMUTED }}"
      Django: "{{ PREMUTED }}[Django](https://www.djangoproject.com/){{ POSTMUTED }}"
      DRF: "{{ PREMUTED }}[Django REST framework](https://www.django-rest-framework.org/){{ POSTMUTED }}"
      GitHub: "{{ PREMUTED }}[GitHub](https://www.github.com/){{ POSTMUTED }}"
      JavaScript: "{{ PREMUTED }}[JavaScript](https://www.javascript.com/){{ POSTMUTED }}"
      Paramiko: "{{ PREMUTED }}[Paramiko](https://www.paramiko.org/){{ POSTMUTED }}"
      PostgreSQL: "{{ PREMUTED }}[PostgreSQL](https://www.postgresql.org/){{ POSTMUTED }}"
      pylabber: "{{ PREMUTED }}[*pylabber*](https://www.github.com/TheLabbingProject/pylabber){{ POSTMUTED }}"
      VueJS: "{{ PREMUTED }}[Vue.js](https://vuejs.org/){{ POSTMUTED }}"

# Parse and render settings
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
