###############################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html
###############################################################################

# Book settings
title: Ph.D. Thesis
author: Zvi Baratz
copyright: "2021"
logo: logo.png
exclude_patterns: ["*skip*"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ZviBaratz/PhD
  path_to_book: src/book
  branch: master

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: favicon.jpg
  baseurl: "https://zvibaratz.github.io/phd/front.html"
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""

# Declare primary language.
# See: https://jupyterbook.org/advanced/html.html#configuring-to-improve-accessibility
sphinx:
  config:
    language: en
    bibtex_reference_style: author_year
    myst_substitutions:
      # Acronyms
      PREACRONYM: '<span class="acronym-ref">'
      POSTACRONYM: "</span>"
      ABIDE: "{{ PREACRONYM }}{ref}`ABIDE <lists:acronyms>`{{ POSTACRONYM }}"
      ADNI: "{{ PREACRONYM }}{ref}`ADNI <lists:acronyms>`{{ POSTACRONYM }}"
      BFI: "{{ PREACRONYM }}{ref}`BFI <lists:acronyms>`{{ POSTACRONYM }}"
      BIDS: "{{ PREACRONYM }}{ref}`BIDS <lists:acronyms>`{{ POSTACRONYM }}"
      CI: "{{ PREACRONYM }}{ref}`CI <lists:acronyms>`{{ POSTACRONYM }}"
      COINS: "{{ PREACRONYM }}{ref}`COINS <lists:acronyms>`{{ POSTACRONYM }}"
      CSS: "{{ PREACRONYM }}{ref}`CSS <lists:acronyms>`{{ POSTACRONYM }}"
      DICOM: "{{ PREACRONYM }}{ref}`DICOM <lists:acronyms>`{{ POSTACRONYM }}"
      dMRI: "{{ PREACRONYM }}{ref}`dMRI <lists:acronyms>`{{ POSTACRONYM }}"
      EDA: "{{ PREACRONYM }}{ref}`EDA <lists:acronyms>`{{ POSTACRONYM }}"
      ER: "{{ PREACRONYM }}{ref}`ER <lists:acronyms>`{{ POSTACRONYM }}"
      fMRI: "{{ PREACRONYM }}{ref}`fMRI <lists:acronyms>`{{ POSTACRONYM }}"
      FOSS: "{{ PREACRONYM }}{ref}`FOSS <lists:acronyms>`{{ POSTACRONYM }}"
      GUI: "{{ PREACRONYM }}{ref}`GUI <lists:acronyms>`{{ POSTACRONYM }}"
      HCP: "{{ PREACRONYM }}{ref}`HCP <lists:acronyms>`{{ POSTACRONYM }}"
      HTML: "{{ PREACRONYM }}{ref}`HTML <lists:acronyms>`{{ POSTACRONYM }}"
      JSON: "{{ PREACRONYM }}{ref}`JSON <lists:acronyms>`{{ POSTACRONYM }}"
      JSP: "{{ PREACRONYM }}{ref}`JSP <lists:acronyms>`{{ POSTACRONYM }}"
      LORIS: "{{ PREACRONYM }}{ref}`LORIS <lists:acronyms>`{{ POSTACRONYM }}"
      MPRAGE: "{{ PREACRONYM }}{ref}`MPRAGE <lists:acronyms>`{{ POSTACRONYM }}"
      MR: "{{ PREACRONYM }}{ref}`MR <lists:acronyms>`{{ POSTACRONYM }}"
      MRI: "{{ PREACRONYM }}{ref}`MRI <lists:acronyms>`{{ POSTACRONYM }}"
      NIfTI: "{{ PREACRONYM }}{ref}`NIfTI <lists:acronyms>`{{ POSTACRONYM }}"
      PHI: "{{ PREACRONYM }}{ref}`PHI <lists:acronyms>`{{ POSTACRONYM }}"
      PHP: "{{ PREACRONYM }}{ref}`PHP <lists:acronyms>`{{ POSTACRONYM }}"
      RDM: "{{ PREACRONYM }}{ref}`RDM <lists:acronyms>`{{ POSTACRONYM }}"
      rsfMRI: "{{ PREACRONYM }}{ref}`rs-fMRI <lists:acronyms>`{{ POSTACRONYM }}"
      sMRI: "{{ PREACRONYM }}{ref}`sMRI <lists:acronyms>`{{ POSTACRONYM }}"
      SNR: "{{ PREACRONYM }}{ref}`SNR <lists:acronyms>`{{ POSTACRONYM }}"
      SQL: "{{ PREACRONYM }}{ref}`SQL <lists:acronyms>`{{ POSTACRONYM }}"
      SD: "{{ PREACRONYM }}{ref}`SD <lists:acronyms>`{{ POSTACRONYM }}"
      T1w: "{{ PREACRONYM }}{ref}`T1w <lists:acronyms>`{{ POSTACRONYM }}"
      T2w: "{{ PREACRONYM }}{ref}`T2w <lists:acronyms>`{{ POSTACRONYM }}"
      XNAT: "{{ PREACRONYM }}{ref}`XNAT <lists:acronyms>`{{ POSTACRONYM }}"
      # HTML & CSS
      greenCheckmark: '<p class="table-icon" style="color: green;"><i class="fas fa-check-circle"></i></p>'
      greenCheckmarkStarred: '<p class="table-icon" style="color: green;"><i class="fas fa-check-circle"></i><span style="color: black;">*</span></p>'
      redCross: '<p class="table-icon" style="color: red;"><i class="fas fa-times-circle"></i></p>'

# Parse and render settings
parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
